% Front-to-back target order
desired_order = {
    'Fp1','FPz','FP2', ...
    'AF7','AF3','AFz','AF4','AF8', ...
    'F7','F5','F3','F1','Fz','F2','F4','F6','F8', ...
    'FT7','FT8', ...
    'FC5','FC3','FC1','FCz','FC2','FC4','FC6', ...
    'T7','T8', ...
    'C5','C3','C1','Cz','C2','C4','C6', ...
    'TP7','TP8', ...
    'CP5','CP3','CP1','CPz','CP2','CP4','CP6', ...
    'P9','P7','P5','P3','P1','Pz','P2','P4','P6','P8','P10', ...
    'PO7','PO3','POz','PO4','PO8', ...
    'O1','Oz','Iz','O2'
};

% Map current labels -> desired positions, then sort
current_labels = {EEG.chanlocs.labels};
[found, loc_in_desired] = ismember(lower(current_labels), lower(desired_order));
if ~all(found)
    missing = current_labels(~found);
    error('Missing in desired_order: %s', strjoin(missing, ', '));
end
[~, order_idx] = sort(loc_in_desired, 'ascend');

% Reorder data
EEG.chanlocs = EEG.chanlocs(order_idx);
EEG.data = EEG.data(order_idx,:);